import { Product, Category, SupportTicket } from './types';

export const mockProducts: Product[] = [
  {
    id: 1,
    name: 'Wireless Bluetooth Headphones',
    slug: 'wireless-bluetooth-headphones',
    price: 89.99,
    image: 'https://images.pexels.com/photos/3945683/pexels-photo-3945683.jpeg?auto=compress&cs=tinysrgb&w=500',
    description: 'Premium wireless headphones with noise cancellation and 30-hour battery life.',
    category: 'Electronics',
    categorySlug: 'electronics',
    stock: 15,
    rating: 4.5,
    reviews: 128,
    brand: 'AudioTech',
    tags: ['wireless', 'bluetooth', 'noise-cancellation'],
  },
  {
    id: 2,
    name: 'Smart Watch Series 8',
    slug: 'smart-watch-series-8',
    price: 399.99,
    image: 'https://images.pexels.com/photos/393047/pexels-photo-393047.jpeg?auto=compress&cs=tinysrgb&w=500',
    description: 'Advanced smartwatch with health monitoring, GPS, and cellular connectivity.',
    category: 'Electronics',
    categorySlug: 'electronics',
    stock: 8,
    rating: 4.8,
    reviews: 89,
    brand: 'TechWatch',
    tags: ['smartwatch', 'fitness', 'gps'],
  },
  {
    id: 3,
    name: 'Organic Cotton T-Shirt',
    slug: 'organic-cotton-t-shirt',
    price: 29.99,
    image: 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=500',
    description: 'Comfortable and sustainable organic cotton t-shirt in multiple colors.',
    category: 'Clothing',
    categorySlug: 'clothing',
    stock: 25,
    rating: 4.2,
    reviews: 45,
    brand: 'EcoWear',
    tags: ['organic', 'cotton', 'sustainable'],
  },
  {
    id: 4,
    name: 'Professional Camera Lens',
    slug: 'professional-camera-lens',
    price: 799.99,
    image: 'https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&w=500',
    description: 'High-quality 50mm f/1.8 lens for professional photography.',
    category: 'Electronics',
    categorySlug: 'electronics',
    stock: 5,
    rating: 4.9,
    reviews: 234,
    brand: 'ProLens',
    tags: ['camera', 'lens', 'photography'],
  },
  {
    id: 5,
    name: 'Luxury Leather Wallet',
    slug: 'luxury-leather-wallet',
    price: 149.99,
    image: 'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=500',
    description: 'Handcrafted genuine leather wallet with RFID protection.',
    category: 'Accessories',
    categorySlug: 'accessories',
    stock: 12,
    rating: 4.6,
    reviews: 67,
    brand: 'LeatherCraft',
    tags: ['leather', 'wallet', 'rfid'],
  },
  {
    id: 6,
    name: 'Minimalist Desk Lamp',
    slug: 'minimalist-desk-lamp',
    price: 79.99,
    image: 'https://images.pexels.com/photos/416320/pexels-photo-416320.jpeg?auto=compress&cs=tinysrgb&w=500',
    description: 'Modern LED desk lamp with adjustable brightness and USB charging port.',
    category: 'Home',
    categorySlug: 'home',
    stock: 18,
    rating: 4.4,
    reviews: 92,
    brand: 'ModernHome',
    tags: ['led', 'desk', 'adjustable'],
  },
];

export const mockCategories: Category[] = [
  {
    id: 1,
    name: 'Electronics',
    slug: 'electronics',
    description: 'Latest gadgets and electronic devices',
    image: 'https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg?auto=compress&cs=tinysrgb&w=500',
    productCount: 3,
  },
  {
    id: 2,
    name: 'Clothing',
    slug: 'clothing',
    description: 'Fashion and apparel for all occasions',
    image: 'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=500',
    productCount: 1,
  },
  {
    id: 3,
    name: 'Accessories',
    slug: 'accessories',
    description: 'Complete your look with our accessories',
    image: 'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=500',
    productCount: 1,
  },
  {
    id: 4,
    name: 'Home',
    slug: 'home',
    description: 'Home decor and furniture',
    image: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=500',
    productCount: 1,
  },
];

export const mockSupportTickets: SupportTicket[] = [
  {
    id: 1,
    subject: 'Order delivery issue',
    message: 'My order #1234 has not been delivered yet. Can you please check the status?',
    status: 'in-progress',
    priority: 'medium',
    createdAt: '2024-01-15T10:30:00Z',
    updatedAt: '2024-01-16T14:20:00Z',
    responses: [
      {
        id: 1,
        message: 'Thank you for contacting us. We are checking with our delivery partner.',
        isStaff: true,
        createdAt: '2024-01-16T14:20:00Z',
      },
    ],
  },
  {
    id: 2,
    subject: 'Product return request',
    message: 'I would like to return the headphones I purchased last week.',
    status: 'resolved',
    priority: 'low',
    createdAt: '2024-01-10T09:15:00Z',
    updatedAt: '2024-01-12T16:45:00Z',
  },
];